import sharp from "sharp";
import path from "node:path";
import { nanoid } from "nanoid";
import { getStyle } from "../lib/styles.js";
import { getFormat } from "../lib/formats.js";
import { STORAGE_DIR } from "../lib/storage.js";

/**
 * ImageAdProvider interface
 * --------------------------------
 * Any real provider (e.g. a hosted image-generation API) should implement:
 *
 *   async generate({ sourceImagePath, prompt, styleId, formatId }) : Promise<{ filePath, width, height }>
 *
 * `prompt` is produced by lib/promptEngine.js#buildImagePrompt. `sourceImagePath`
 * is the path to the user's uploaded product photo, in case the provider needs
 * to send the raw image (image-to-image / reference-image APIs).
 *
 * The mock implementation below fakes a plausible ad composition using sharp
 * (product image composited onto a styled background with style-appropriate
 * text) purely so the full app flow can be demoed without any API keys.
 * Swap MockImageAdProvider for a real provider class that satisfies the same
 * interface, and nothing else in the app needs to change.
 */
export class ImageAdProvider {
  async generate(_params) {
    throw new Error("Not implemented — use a concrete provider (e.g. MockImageAdProvider).");
  }
}

export class MockImageAdProvider extends ImageAdProvider {
  async generate({ sourceImagePath, prompt, styleId, formatId, category }) {
    const style = getStyle(styleId);
    const format = getFormat(formatId);
    const { width, height } = format;

    // Background: soft gradient in the style's accent color.
    const background = await sharp({
      create: {
        width,
        height,
        channels: 4,
        background: style.accent,
      },
    })
      .png()
      .toBuffer();

    // Fit the product photo into ~72% of the canvas, centered, with a subtle
    // drop shadow effect approximated via a soft dark rectangle underneath.
    const productMaxW = Math.round(width * 0.72);
    const productMaxH = Math.round(height * 0.62);

    const productBuf = await sharp(sourceImagePath)
      .resize({ width: productMaxW, height: productMaxH, fit: "inside", withoutEnlargement: false })
      .toBuffer();
    const productMeta = await sharp(productBuf).metadata();

    const productLeft = Math.round((width - productMeta.width) / 2);
    const productTop = Math.round((height - productMeta.height) / 2 - height * 0.03);

    // Style label + simulated CTA as an SVG text overlay.
    const captionSvg = buildCaptionSvg({ width, height, style, category });

    const composed = sharp(background).composite([
      { input: productBuf, left: productLeft, top: Math.max(productTop, 0) },
      { input: Buffer.from(captionSvg), left: 0, top: 0 },
    ]);

    const fileName = `ad-image-${nanoid(8)}.png`;
    const outPath = path.join(STORAGE_DIR, "generated", fileName);
    await composed.png().toFile(outPath);

    return {
      filePath: outPath,
      publicPath: `/assets/generated/${fileName}`,
      width,
      height,
      promptUsed: prompt,
      providerNote:
        "Generated by MockImageAdProvider (local composite). Replace with a real image-generation provider for production-quality creative — see README.",
    };
  }
}

function buildCaptionSvg({ width, height, style, category }) {
  const label = style.label.toUpperCase();
  const sub = category ? `AI-GENERATED AD · ${category.toUpperCase()}` : "AI-GENERATED AD";

  // Band height is driven by height (so it reads as a proportionate footer
  // on any aspect ratio), but font size must be capped by WIDTH — on a tall
  // 9:16 canvas, height-driven sizing alone produces text wider than the
  // canvas. We compute an uncapped size from band height, then clamp it so
  // the label can never exceed ~92% of the canvas width, and force-fit with
  // textLength as a belt-and-braces guard against any remaining overflow.
  const bandHeight = Math.round(height * 0.12);
  const maxTextWidth = width * 0.92;

  const labelSizeByHeight = bandHeight * 0.34;
  const labelSizeByWidth = maxTextWidth / (label.length * 0.62); // ~0.62em avg glyph width, bold
  const labelSize = Math.max(10, Math.round(Math.min(labelSizeByHeight, labelSizeByWidth)));
  const labelWidthEstimate = label.length * labelSize * 0.62;
  const labelLengthAttr =
    labelWidthEstimate > maxTextWidth ? ` textLength="${Math.round(maxTextWidth)}" lengthAdjust="spacingAndGlyphs"` : "";

  const subSizeByHeight = bandHeight * 0.16;
  const subSizeByWidth = maxTextWidth / (sub.length * 0.55);
  const subSize = Math.max(8, Math.round(Math.min(subSizeByHeight, subSizeByWidth)));
  const subWidthEstimate = sub.length * subSize * 0.55;
  const subLengthAttr =
    subWidthEstimate > maxTextWidth ? ` textLength="${Math.round(maxTextWidth)}" lengthAdjust="spacingAndGlyphs"` : "";

  return `
  <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
    <rect x="0" y="${height - bandHeight}" width="${width}" height="${bandHeight}" fill="${style.textColor}" opacity="0.88" />
    <text x="${width / 2}" y="${height - bandHeight / 2 - 6}" font-family="DejaVu Sans, sans-serif" font-size="${labelSize}" font-weight="bold" fill="${style.accent}" text-anchor="middle"${labelLengthAttr}>${escapeXml(label)}</text>
    <text x="${width / 2}" y="${height - bandHeight / 2 + Math.round(bandHeight * 0.26)}" font-family="DejaVu Sans, sans-serif" font-size="${subSize}" fill="${style.accent}" text-anchor="middle" opacity="0.85"${subLengthAttr}>${escapeXml(sub)}</text>
  </svg>`;
}

function escapeXml(str) {
  return String(str).replace(/[<>&'"]/g, (c) => ({
    "<": "&lt;",
    ">": "&gt;",
    "&": "&amp;",
    "'": "&apos;",
    '"': "&quot;",
  }[c]));
}
