import path from "node:path";
import { spawn } from "node:child_process";
import { nanoid } from "nanoid";
import sharp from "sharp";
import { STORAGE_DIR } from "../lib/storage.js";
import { getFormat } from "../lib/formats.js";
import { getStyle } from "../lib/styles.js";

/**
 * VideoAdProvider interface
 * --------------------------------
 * Any real provider (e.g. an image-to-video generation API) should implement:
 *
 *   async generate({ sourceImagePath, prompt, styleId, formatId, onProgress }) : Promise<{ filePath }>
 *
 * This is called from an async job (see lib/jobQueue.js) because real
 * video-generation APIs are typically slow (tens of seconds to minutes) and
 * often expose a submit + poll or webhook pattern rather than a single
 * synchronous call. The mock implementation below simulates that same
 * async shape, but produces a REAL playable .mp4 — a Ken Burns pan/zoom over
 * the generated static ad image with a CTA text overlay — using ffmpeg, so
 * the full flow can be demoed end-to-end with no API keys.
 */
export class VideoAdProvider {
  async generate(_params) {
    throw new Error("Not implemented — use a concrete provider (e.g. MockVideoAdProvider).");
  }
}

export class MockVideoAdProvider extends VideoAdProvider {
  async generate({ sourceImagePath, styleId, formatId, prompt }) {
    const style = getStyle(styleId);
    const format = getFormat(formatId);
    const duration = 5; // seconds
    const fps = 30;

    // ffmpeg's zoompan needs a source frame at least as large as the target;
    // upscale a bit first so the zoom has room to move without pixelating.
    const upscaled = path.join(STORAGE_DIR, "generated", `video-src-${nanoid(6)}.png`);
    await sharp(sourceImagePath)
      .resize({ width: format.width * 2, height: format.height * 2, fit: "cover" })
      .toFile(upscaled);

    const fileName = `ad-video-${nanoid(8)}.mp4`;
    const outPath = path.join(STORAGE_DIR, "generated", fileName);

    const ctaText = ctaFor(style).replace(/'/g, "’").replace(/:/g, "\\:");

    const zoompan = `zoompan=z='min(zoom+0.0015,1.15)':d=${duration * fps}:s=${format.width}x${format.height}:fps=${fps}`;
    const drawtext =
      `drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='${ctaText}':` +
      `fontcolor=white:fontsize=${Math.round(format.width * 0.06)}:x=(w-text_w)/2:y=h-(h*0.16):` +
      `box=1:boxcolor=black@0.55:boxborderw=20:enable='gte(t,${duration - 2})'`;

    const filter = `${zoompan},${drawtext},fade=t=in:st=0:d=0.4,fade=t=out:st=${duration - 0.4}:d=0.4`;

    await runFfmpeg([
      "-y",
      "-loop",
      "1",
      "-i",
      upscaled,
      "-t",
      String(duration),
      "-vf",
      filter,
      "-c:v",
      "libx264",
      "-pix_fmt",
      "yuv420p",
      "-movflags",
      "+faststart",
      outPath,
    ]);

    return {
      filePath: outPath,
      publicPath: `/assets/generated/${fileName}`,
      durationSeconds: duration,
      width: format.width,
      height: format.height,
      promptUsed: prompt,
      providerNote:
        "Generated by MockVideoAdProvider (local ffmpeg pan/zoom + CTA overlay, not a real AI video model). Replace with a real image-to-video generation provider for production — see README.",
    };
  }
}

function ctaFor(style) {
  switch (style.id) {
    case "bold-sale":
      return "Shop the Sale — Limited Time";
    case "seasonal":
      return "Get Yours This Season";
    case "ugc":
      return "See Why Everyone’s Talking About It";
    case "lifestyle":
      return "Made for Real Life — Shop Now";
    default:
      return "Shop Now";
  }
}

function runFfmpeg(args) {
  return new Promise((resolve, reject) => {
    const proc = spawn("ffmpeg", args);
    let stderr = "";
    proc.stderr.on("data", (d) => (stderr += d.toString()));
    proc.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`ffmpeg exited with code ${code}: ${stderr.slice(-800)}`));
    });
    proc.on("error", reject);
  });
}
